name: EasyCabinet

services:

  frontend:
    container_name: easycabinet-frontend
    ports:
      - ${WEB_PORT}:80
    build:
      context: packages/frontend
      dockerfile: Dockerfile
    networks:
      - aurora-network
    restart: always

  backend:
    container_name: easycabinet-backend
    build:
      context: packages/backend
      dockerfile: Dockerfile
    networks:
      - aurora-network
    depends_on:
      - keydb
      - mysql
      - minio
    restart: always

  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_DEFAULT_BUCKETS=mine:download
      - MINIO_BROWSER=off
    networks:
      - aurora-network
    #restart: always

  keydb:
    image: bitnami/keydb:latest
    container_name: keydb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - aurora-network
    #restart: always

  mysql:
    image: mysql:lts
    container_name: mysql
    networks:
      - aurora-network
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=mine
      - MYSQL_USER=mine
      - MYSQL_PASSWORD=mine
    #restart: always

networks:
  aurora-network:
    attachable: true